### ISSUE TITLE
__precompile__() occuring after module rather than before

### ISSUE THREAD

**Issue by kilminster** [samoconnor/AWSCore.jl#1]
Reading the documentation (by typing `?__precompile__` at the REPL), it seems that "Typically, `__precompile__()` should occur before the module declaration in the file...".

I've no idea how important this actually is, however today I had some problems with julia appearing to hang (or at least take a very long time in precompilation) and moving the `__precompile__()` out of the module definition in AWSCore.jl seemed to help.  I haven't actually gotten to the bottom of what was going on, so it could have just been coincidence.

**Comment by samoconnor** [comment]
Thanks for that @kilminster.
I've moved the `__precompile__()` calls to the top of the file for the various `AWS*` modules.

The change should be available through `Pkg.update()` as soon as https://github.com/JuliaLang/METADATA.jl/pull/4618 is merged.

**Comment by kilminster** [comment]
You're welcome.  I still don't know if it actually matters...

**Comment by samoconnor** [comment]
I'm not sure either, but it certainly makes sense to follow the usual pattern.
(Maybe it explains occasional messages something like "warning module replaced" that I've seen from time to time)

**Comment by jingpengwu** [comment]
It seems that the HttpParser and MbedTLS do not support precompilation. putting `__precompile__` before them created this issue..

```
using AWSCore
INFO: Recompiling stale cache file /usr/people/jingpeng/.julia/lib/v0.4/AWSCore.ji for module AWSCore.
INFO: Recompiling stale cache file /usr/people/jingpeng/.julia/lib/v0.4/Requests.ji for module Requests.
WARNING: Module MbedTLS uuid did not match cache file
  This is likely because module MbedTLS does not support  precompilation but is imported by a module that does.
WARNING: deserialization checks failed while attempting to load cache from /usr/people/jingpeng/.julia/lib/v0.4/AWSCore.ji
INFO: Precompiling module AWSCore...
INFO: Recompiling stale cache file /usr/people/jingpeng/.julia/lib/v0.4/AWSCore.ji for module AWSCore.
WARNING: Module HttpParser uuid did not match cache file
  This is likely because module HttpParser does not support  precompilation but is imported by a module that does.
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at ./loading.jl:268

```

my version info
```
versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```
