### ISSUE TITLE
Any plans for supporting SES ?

### ISSUE THREAD

**Issue by aviks** [samoconnor/AWSCore.jl#2]
Thanks!

**Comment by samoconnor** [comment]
Hi Avik,

Porting my Tcl SES code to Julia has been on my todo list for a while.

Here it is: https://github.com/samoconnor/AWSSES.jl

Once https://github.com/JuliaLang/METADATA.jl/pull/4659 is merged you should be able to do `Pkg.add("AWSSES")` please let me know if you find any bugs, or missing features.

Cheers,

Sam

**Comment by aviks** [comment]
Hey, thanks! Will try it out.
