### ISSUE TITLE
dynamodb support

### ISSUE THREAD

**Issue by samuelpowell** [samoconnor/AWSCore.jl#7]
The AWSCore documentation gives an example of using DynamoDB
```
r = dynamodb(aws, "ListTables", "{}")
println(r)
```
but I can't see that you have published a package which provides this functionality. I do note however your example in dls/DynamoDB.jl#4. Does this code relate to that example, or do you plan to release a module for DynamoDB?

**Comment by samoconnor** [comment]
Hi @samuelpowell 
I've added a reference to your DynamoDB fork in `README.md`: https://github.com/samoconnor/AWSCore.jl/commit/b93fc9ea62403b43e1d8f453cbd83b367b929e0d

**Comment by s2maki** [comment]
We had a lot of problems with AWS.jl and DynamoDB.jl.  As a result, I have a DynamoDB package that was built against AWSCore.jl initially, is more complete, and is more aligned with the style of @samoconnor's suite.  I hope to be able to publish it soon.
